#-------------------------------------------------------------------------
#
# Makefile for backend/utils/mb/conversion_procs
#
# Portions Copyright (c) 1996-2021, PostgreSQL Global Development Group
# Portions Copyright (c) 1994, Regents of the University of California
#
# src/backend/utils/mb/conversion_procs/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/mb/conversion_procs
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = \
	utf8_and_iso8859_1

$(recurse)
