# src/test/modules/Makefile

subdir = src/test/modules
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = \
		  delay_execution \
		  test_misc


$(recurse)
$(recurse_always)
