# src/test/modules/Makefile

subdir = src/test/modules
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = \
		  delay_execution \
		  dummy_index_am \
		  libpq_pipeline \
		  plsample \
		  snapshot_too_old \
		  test_bloomfilter \
		  test_custom_types \
		  test_extensions \
		  test_integerset \
		  test_misc \
		  test_predtest \
		  test_rbtree \
		  test_shm_mq \
		  worker_spi

$(recurse)
$(recurse_always)
