#
# Makefile for storage/ipc
#
# src/backend/storage/ipc/Makefile
#

subdir = src/backend/storage/ipc
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	ipc.o \
	ipci.o \
	latch.o \
	pmsignal.o \
	procarray.o \
	procsignal.o \
	shmem.o \
	shmqueue.o \
	signalfuncs.o \
	sinval.o \
	sinvaladt.o \
	standby.o

include $(top_srcdir)/src/backend/common.mk
