# contrib/Makefile

subdir = contrib
top_builddir = ..
include $(top_builddir)/src/Makefile.global

SUBDIRS = \
		amcheck		\
		pageinspect	\
		pg_buffercache	\
		pg_freespacemap \
		pg_surgery	\
		pgrowlocks	\
		pgstattuple	\
		pg_visibility	\
		spi

$(recurse)
$(recurse_always)
