cat >conf330493subs.awk <<_ACEOF
LTLIBOBJS!$LTLIBOBJS$ac_delim
vpath_build!$vpath_build$ac_delim
PG_SYSROOT!$PG_SYSROOT$ac_delim
PG_VERSION_NUM!$PG_VERSION_NUM$ac_delim
PROVE!$PROVE$ac_delim
DBTOEPUB!$DBTOEPUB$ac_delim
FOP!$FOP$ac_delim
XSLTPROC!$XSLTPROC$ac_delim
XMLLINT!$XMLLINT$ac_delim
TCL_SHLIB_LD_LIBS!$TCL_SHLIB_LD_LIBS$ac_delim
TCL_SHARED_BUILD!$TCL_SHARED_BUILD$ac_delim
TCL_LIB_SPEC!$TCL_LIB_SPEC$ac_delim
TCL_LIBS!$TCL_LIBS$ac_delim
TCL_INCLUDE_SPEC!$TCL_INCLUDE_SPEC$ac_delim
TCL_CONFIG_SH!$TCL_CONFIG_SH$ac_delim
TCLSH!$TCLSH$ac_delim
PG_CRC32C_OBJS!$PG_CRC32C_OBJS$ac_delim
CFLAGS_ARMV8_CRC32C!$CFLAGS_ARMV8_CRC32C$ac_delim
CFLAGS_SSE42!$CFLAGS_SSE42$ac_delim
LIBOBJS!$LIBOBJS$ac_delim
UUID_LIBS!$UUID_LIBS$ac_delim
PTHREAD_CFLAGS!$PTHREAD_CFLAGS$ac_delim
PTHREAD_LIBS!$PTHREAD_LIBS$ac_delim
PTHREAD_CC!$PTHREAD_CC$ac_delim
ax_pthread_config!$ax_pthread_config$ac_delim
EGREP!$EGREP$ac_delim
GREP!$GREP$ac_delim
SED!$SED$ac_delim
ZIC!$ZIC$ac_delim
python_additional_libs!$python_additional_libs$ac_delim
python_libspec!$python_libspec$ac_delim
python_libdir!$python_libdir$ac_delim
python_includespec!$python_includespec$ac_delim
python_version!$python_version$ac_delim
python_majorversion!$python_majorversion$ac_delim
PYTHON!$PYTHON$ac_delim
perl_embed_ldflags!$perl_embed_ldflags$ac_delim
perl_embed_ccflags!$perl_embed_ccflags$ac_delim
perl_includespec!$perl_includespec$ac_delim
perl_useshrplib!$perl_useshrplib$ac_delim
perl_privlibexp!$perl_privlibexp$ac_delim
perl_archlibexp!$perl_archlibexp$ac_delim
PERL!$PERL$ac_delim
FLEXFLAGS!$FLEXFLAGS$ac_delim
FLEX!$FLEX$ac_delim
BISONFLAGS!$BISONFLAGS$ac_delim
BISON!$BISON$ac_delim
MKDIR_P!$MKDIR_P$ac_delim
LN_S!$LN_S$ac_delim
TAR!$TAR$ac_delim
install_bin!$install_bin$ac_delim
INSTALL_DATA!$INSTALL_DATA$ac_delim
INSTALL_SCRIPT!$INSTALL_SCRIPT$ac_delim
INSTALL_PROGRAM!$INSTALL_PROGRAM$ac_delim
WINDRES!$WINDRES$ac_delim
DLLWRAP!$DLLWRAP$ac_delim
DLLTOOL!$DLLTOOL$ac_delim
AR!$AR$ac_delim
STRIP_SHARED_LIB!$STRIP_SHARED_LIB$ac_delim
STRIP_STATIC_LIB!$STRIP_STATIC_LIB$ac_delim
STRIP!$STRIP$ac_delim
RANLIB!$RANLIB$ac_delim
with_gnu_ld!$with_gnu_ld$ac_delim
LD!$LD$ac_delim
LDFLAGS_SL!$LDFLAGS_SL$ac_delim
LDFLAGS_EX!$LDFLAGS_EX$ac_delim
LZ4_LIBS!$LZ4_LIBS$ac_delim
LZ4_CFLAGS!$LZ4_CFLAGS$ac_delim
with_lz4!$with_lz4$ac_delim
with_zlib!$with_zlib$ac_delim
with_system_tzdata!$with_system_tzdata$ac_delim
with_libxslt!$with_libxslt$ac_delim
XML2_LIBS!$XML2_LIBS$ac_delim
XML2_CFLAGS!$XML2_CFLAGS$ac_delim
XML2_CONFIG!$XML2_CONFIG$ac_delim
with_libxml!$with_libxml$ac_delim
with_uuid!$with_uuid$ac_delim
with_readline!$with_readline$ac_delim
with_python!$with_python$ac_delim
with_perl!$with_perl$ac_delim
with_tcl!$with_tcl$ac_delim
ICU_LIBS!$ICU_LIBS$ac_delim
ICU_CFLAGS!$ICU_CFLAGS$ac_delim
with_icu!$with_icu$ac_delim
enable_thread_safety!$enable_thread_safety$ac_delim
INCLUDES!$INCLUDES$ac_delim
autodepend!$autodepend$ac_delim
PKG_CONFIG_LIBDIR!$PKG_CONFIG_LIBDIR$ac_delim
PKG_CONFIG_PATH!$PKG_CONFIG_PATH$ac_delim
PKG_CONFIG!$PKG_CONFIG$ac_delim
GCC!$GCC$ac_delim
CPP!$CPP$ac_delim
CFLAGS_SL!$CFLAGS_SL$ac_delim
BITCODE_CXXFLAGS!$BITCODE_CXXFLAGS$ac_delim
BITCODE_CFLAGS!$BITCODE_CFLAGS$ac_delim
CFLAGS_VECTORIZE!$CFLAGS_VECTORIZE$ac_delim
CFLAGS_UNROLL_LOOPS!$CFLAGS_UNROLL_LOOPS$ac_delim
PERMIT_DECLARATION_AFTER_STATEMENT!$PERMIT_DECLARATION_AFTER_STATEMENT$ac_delim
LLVM_BINPATH!$LLVM_BINPATH$ac_delim
LLVM_CXXFLAGS!$LLVM_CXXFLAGS$ac_delim
LLVM_CFLAGS!$LLVM_CFLAGS$ac_delim
LLVM_CPPFLAGS!$LLVM_CPPFLAGS$ac_delim
LLVM_LIBS!$LLVM_LIBS$ac_delim
CLANG!$CLANG$ac_delim
LLVM_CONFIG!$LLVM_CONFIG$ac_delim
AWK!$AWK$ac_delim
with_llvm!$with_llvm$ac_delim
SUN_STUDIO_CC!$SUN_STUDIO_CC$ac_delim
ac_ct_CXX!$ac_ct_CXX$ac_delim
CXXFLAGS!$CXXFLAGS$ac_delim
CXX!$CXX$ac_delim
OBJEXT!$OBJEXT$ac_delim
EXEEXT!$EXEEXT$ac_delim
ac_ct_CC!$ac_ct_CC$ac_delim
CPPFLAGS!$CPPFLAGS$ac_delim
LDFLAGS!$LDFLAGS$ac_delim
CFLAGS!$CFLAGS$ac_delim
CC!$CC$ac_delim
enable_tap_tests!$enable_tap_tests$ac_delim
enable_dtrace!$enable_dtrace$ac_delim
DTRACEFLAGS!$DTRACEFLAGS$ac_delim
DTRACE!$DTRACE$ac_delim
enable_coverage!$enable_coverage$ac_delim
GENHTML!$GENHTML$ac_delim
LCOV!$LCOV$ac_delim
GCOV!$GCOV$ac_delim
enable_debug!$enable_debug$ac_delim
enable_rpath!$enable_rpath$ac_delim
default_port!$default_port$ac_delim
PORTNAME!$PORTNAME$ac_delim
host_os!$host_os$ac_delim
host_vendor!$host_vendor$ac_delim
host_cpu!$host_cpu$ac_delim
host!$host$ac_delim
build_os!$build_os$ac_delim
build_vendor!$build_vendor$ac_delim
build_cpu!$build_cpu$ac_delim
build!$build$ac_delim
PG_MAJORVERSION!$PG_MAJORVERSION$ac_delim
target_alias!$target_alias$ac_delim
host_alias!$host_alias$ac_delim
build_alias!$build_alias$ac_delim
LIBS!$LIBS$ac_delim
ECHO_T!$ECHO_T$ac_delim
ECHO_N!$ECHO_N$ac_delim
ECHO_C!$ECHO_C$ac_delim
DEFS!$DEFS$ac_delim
mandir!$mandir$ac_delim
localedir!$localedir$ac_delim
libdir!$libdir$ac_delim
psdir!$psdir$ac_delim
pdfdir!$pdfdir$ac_delim
dvidir!$dvidir$ac_delim
htmldir!$htmldir$ac_delim
infodir!$infodir$ac_delim
docdir!$docdir$ac_delim
oldincludedir!$oldincludedir$ac_delim
includedir!$includedir$ac_delim
localstatedir!$localstatedir$ac_delim
sharedstatedir!$sharedstatedir$ac_delim
sysconfdir!$sysconfdir$ac_delim
datadir!$datadir$ac_delim
datarootdir!$datarootdir$ac_delim
libexecdir!$libexecdir$ac_delim
sbindir!$sbindir$ac_delim
bindir!$bindir$ac_delim
program_transform_name!$program_transform_name$ac_delim
prefix!$prefix$ac_delim
exec_prefix!$exec_prefix$ac_delim
PACKAGE_URL!$PACKAGE_URL$ac_delim
PACKAGE_BUGREPORT!$PACKAGE_BUGREPORT$ac_delim
PACKAGE_STRING!$PACKAGE_STRING$ac_delim
PACKAGE_VERSION!$PACKAGE_VERSION$ac_delim
PACKAGE_TARNAME!$PACKAGE_TARNAME$ac_delim
PACKAGE_NAME!$PACKAGE_NAME$ac_delim
PATH_SEPARATOR!$PATH_SEPARATOR$ac_delim
SHELL!$SHELL$ac_delim
_ACEOF
