#-------------------------------------------------------------------------
#
# Makefile
#	  Makefile for the optimizer
#
# Portions Copyright (c) 1996-2021, PostgreSQL Global Development Group
# Portions Copyright (c) 1994, Regents of the University of California
#
# src/backend/optimizer/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/optimizer
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = path plan prep util

include $(top_srcdir)/src/backend/common.mk
