#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/commands
#
# IDENTIFICATION
#    src/backend/commands/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/commands
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	alter.o \
	amcmds.o \
	analyze.o \
	cluster.o \
	collationcmds.o \
	dbcommands.o \
	define.o \
	discard.o \
	dropcmds.o \
	explain.o \
	extension.o \
	functioncmds.o \
	indexcmds.o \
	lockcmds.o \
	opclasscmds.o \
	operatorcmds.o \
	portalcmds.o \
	prepare.o \
	proclang.o \
	schemacmds.o \
	statscmds.o \
	tablecmds.o \
	tablespace.o \
	typecmds.o \
	vacuum.o \
	variable.o \
	view.o

include $(top_srcdir)/src/backend/common.mk
