BEGIN {
D["PACKAGE_NAME"]=" \"PostgreSQL\""
D["PACKAGE_TARNAME"]=" \"postgresql\""
D["PACKAGE_VERSION"]=" \"14.23\""
D["PACKAGE_STRING"]=" \"PostgreSQL 14.23\""
D["PACKAGE_BUGREPORT"]=" \"pgsql-bugs@lists.postgresql.org\""
D["PACKAGE_URL"]=" \"https://www.postgresql.org/\""
D["CONFIGURE_ARGS"]=" \" '--enable-debug' '--without-readline'\""
D["PG_MAJORVERSION"]=" \"14\""
D["PG_MAJORVERSION_NUM"]=" 14"
D["PG_MINORVERSION_NUM"]=" 23"
D["PG_VERSION"]=" \"14.23\""
D["DEF_PGPORT"]=" 5432"
D["DEF_PGPORT_STR"]=" \"5432\""
D["BLCKSZ"]=" 8192"
D["RELSEG_SIZE"]=" 131072"
D["XLOG_BLCKSZ"]=" 8192"
D["ENABLE_THREAD_SAFETY"]=" 1"
D["STDC_HEADERS"]=" 1"
D["HAVE_SYS_TYPES_H"]=" 1"
D["HAVE_SYS_STAT_H"]=" 1"
D["HAVE_STDLIB_H"]=" 1"
D["HAVE_STRING_H"]=" 1"
D["HAVE_MEMORY_H"]=" 1"
D["HAVE_STRINGS_H"]=" 1"
D["HAVE_INTTYPES_H"]=" 1"
D["HAVE_STDINT_H"]=" 1"
D["HAVE_UNISTD_H"]=" 1"
D["HAVE_PTHREAD_PRIO_INHERIT"]=" 1"
D["HAVE_PTHREAD"]=" 1"
D["HAVE_STRERROR_R"]=" 1"
D["HAVE_GETPWUID_R"]=" 1"
D["HAVE_GETHOSTBYNAME_R"]=" 1"
D["HAVE_LIBM"]=" 1"
D["HAVE_LIBZ"]=" 1"
D["HAVE_SPINLOCKS"]=" 1"
D["HAVE_ATOMICS"]=" 1"
D["HAVE_EXECINFO_H"]=" 1"
D["HAVE_GETOPT_H"]=" 1"
D["HAVE_IFADDRS_H"]=" 1"
D["HAVE_LANGINFO_H"]=" 1"
D["HAVE_POLL_H"]=" 1"
D["HAVE_SYS_EPOLL_H"]=" 1"
D["HAVE_SYS_IPC_H"]=" 1"
D["HAVE_SYS_PERSONALITY_H"]=" 1"
D["HAVE_SYS_PRCTL_H"]=" 1"
D["HAVE_SYS_RESOURCE_H"]=" 1"
D["HAVE_SYS_SELECT_H"]=" 1"
D["HAVE_SYS_SEM_H"]=" 1"
D["HAVE_SYS_SHM_H"]=" 1"
D["HAVE_SYS_SIGNALFD_H"]=" 1"
D["HAVE_SYS_UIO_H"]=" 1"
D["HAVE_SYS_UN_H"]=" 1"
D["HAVE_TERMIOS_H"]=" 1"
D["HAVE_WCTYPE_H"]=" 1"
D["HAVE_NET_IF_H"]=" 1"
D["HAVE_NETINET_TCP_H"]=" 1"
D["PG_C_PRINTF_ATTRIBUTE"]=" gnu_printf"
D["PG_CXX_PRINTF_ATTRIBUTE"]=" gnu_printf"
D["HAVE_FUNCNAME__FUNC"]=" 1"
D["HAVE__STATIC_ASSERT"]=" 1"
D["HAVE_TYPEOF"]=" 1"
D["HAVE__BUILTIN_TYPES_COMPATIBLE_P"]=" 1"
D["HAVE__BUILTIN_CONSTANT_P"]=" 1"
D["HAVE__BUILTIN_UNREACHABLE"]=" 1"
D["HAVE_COMPUTED_GOTO"]=" 1"
D["HAVE_STRUCT_TM_TM_ZONE"]=" 1"
D["HAVE_STRUCT_SOCKADDR_UN"]=" 1"
D["HAVE_STRUCT_SOCKADDR_STORAGE"]=" 1"
D["HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY"]=" 1"
D["HAVE_STRUCT_ADDRINFO"]=" 1"
D["HAVE_LOCALE_T"]=" 1"
D["restrict"]=" __restrict"
D["pg_restrict"]=" __restrict"
D["HAVE_STRUCT_OPTION"]=" 1"
D["HAVE_X86_64_POPCNTQ"]=" 1"
D["SIZEOF_OFF_T"]=" 8"
D["SIZEOF_BOOL"]=" 1"
D["PG_USE_STDBOOL"]=" 1"
D["HAVE_INT_TIMEZONE"]=" 1"
D["ACCEPT_TYPE_RETURN"]=" int"
D["ACCEPT_TYPE_ARG1"]=" int"
D["ACCEPT_TYPE_ARG2"]=" struct sockaddr *"
D["ACCEPT_TYPE_ARG3"]=" socklen_t"
D["HAVE_BACKTRACE_SYMBOLS"]=" 1"
D["HAVE_CLOCK_GETTIME"]=" 1"
D["HAVE_FDATASYNC"]=" 1"
D["HAVE_GETIFADDRS"]=" 1"
D["HAVE_GETRLIMIT"]=" 1"
D["HAVE_POLL"]=" 1"
D["HAVE_POSIX_FALLOCATE"]=" 1"
D["HAVE_PPOLL"]=" 1"
D["HAVE_READLINK"]=" 1"
D["HAVE_READV"]=" 1"
D["HAVE_SETSID"]=" 1"
D["HAVE_SHM_OPEN"]=" 1"
D["HAVE_STRSIGNAL"]=" 1"
D["HAVE_SYMLINK"]=" 1"
D["HAVE_SYNCFS"]=" 1"
D["HAVE_SYNC_FILE_RANGE"]=" 1"
D["HAVE_USELOCALE"]=" 1"
D["HAVE_WRITEV"]=" 1"
D["HAVE__BUILTIN_BSWAP16"]=" 1"
D["HAVE__BUILTIN_BSWAP32"]=" 1"
D["HAVE__BUILTIN_BSWAP64"]=" 1"
D["HAVE__BUILTIN_CLZ"]=" 1"
D["HAVE__BUILTIN_CTZ"]=" 1"
D["HAVE__BUILTIN_POPCOUNT"]=" 1"
D["HAVE__BUILTIN_FRAME_ADDRESS"]=" 1"
D["HAVE_FSEEKO"]=" 1"
D["HAVE_POSIX_FADVISE"]=" 1"
D["HAVE_DECL_POSIX_FADVISE"]=" 1"
D["HAVE_DECL_FDATASYNC"]=" 1"
D["HAVE_DECL_STRLCAT"]=" 1"
D["HAVE_DECL_STRLCPY"]=" 1"
D["HAVE_DECL_STRNLEN"]=" 1"
D["HAVE_DECL_TIMINGSAFE_BCMP"]=" 0"
D["HAVE_DECL_PREADV"]=" 1"
D["HAVE_DECL_PWRITEV"]=" 1"
D["HAVE_DECL_STRCHRNUL"]=" 1"
D["HAVE_DECL_MEMSET_S"]=" 0"
D["HAVE_DECL_F_FULLFSYNC"]=" 0"
D["HAVE_DECL_RTLD_GLOBAL"]=" 1"
D["HAVE_DECL_RTLD_NOW"]=" 1"
D["HAVE_IPV6"]=" 1"
D["HAVE_DLOPEN"]=" 1"
D["HAVE_EXPLICIT_BZERO"]=" 1"
D["HAVE_GETOPT"]=" 1"
D["HAVE_GETRUSAGE"]=" 1"
D["HAVE_INET_ATON"]=" 1"
D["HAVE_LINK"]=" 1"
D["HAVE_MKDTEMP"]=" 1"
D["HAVE_PREAD"]=" 1"
D["HAVE_PWRITE"]=" 1"
D["HAVE_RANDOM"]=" 1"
D["HAVE_SRANDOM"]=" 1"
D["HAVE_STRLCAT"]=" 1"
D["HAVE_STRLCPY"]=" 1"
D["HAVE_STRNLEN"]=" 1"
D["HAVE_STRTOF"]=" 1"
D["HAVE_PTHREAD_BARRIER_WAIT"]=" 1"
D["HAVE_SETENV"]=" 1"
D["HAVE_UNSETENV"]=" 1"
D["HAVE_GETADDRINFO"]=" 1"
D["HAVE_GETOPT_LONG"]=" 1"
D["HAVE_SYSLOG"]=" 1"
D["HAVE_INT_OPTERR"]=" 1"
D["HAVE_STRTOLL"]=" 1"
D["HAVE_STRTOULL"]=" 1"
D["HAVE_DECL_STRTOLL"]=" 1"
D["HAVE_DECL_STRTOULL"]=" 1"
D["HAVE_LONG_INT_64"]=" 1"
D["PG_INT64_TYPE"]=" long int"
D["INT64_MODIFIER"]=" \"l\""
D["HAVE__BUILTIN_OP_OVERFLOW"]=" 1"
D["SIZEOF_VOID_P"]=" 8"
D["SIZEOF_SIZE_T"]=" 8"
D["SIZEOF_LONG"]=" 8"
D["ALIGNOF_SHORT"]=" 2"
D["ALIGNOF_INT"]=" 4"
D["ALIGNOF_LONG"]=" 8"
D["ALIGNOF_DOUBLE"]=" 8"
D["MAXIMUM_ALIGNOF"]=" 8"
D["PG_INT128_TYPE"]=" __int128"
D["ALIGNOF_PG_INT128_TYPE"]=" 16"
D["HAVE_GCC__SYNC_CHAR_TAS"]=" 1"
D["HAVE_GCC__SYNC_INT32_TAS"]=" 1"
D["HAVE_GCC__SYNC_INT32_CAS"]=" 1"
D["HAVE_GCC__SYNC_INT64_CAS"]=" 1"
D["HAVE_GCC__ATOMIC_INT32_CAS"]=" 1"
D["HAVE_GCC__ATOMIC_INT64_CAS"]=" 1"
D["HAVE__GET_CPUID"]=" 1"
D["USE_SSE42_CRC32C_WITH_RUNTIME_CHECK"]=" 1"
D["USE_UNNAMED_POSIX_SEMAPHORES"]=" 1"
D["USE_SYSV_SHARED_MEMORY"]=" 1"
D["MEMSET_LOOP_LIMIT"]=" 1024"
D["PG_VERSION_STR"]=" \"PostgreSQL 14.23 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit\""
D["PG_VERSION_NUM"]=" 140023"
  for (key in D) D_is_set[key] = 1
  FS = ""
}
/^[\t ]*#[\t ]*(define|undef)[\t ]+[_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ][_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789]*([\t (]|$)/ {
  line = $ 0
  split(line, arg, " ")
  if (arg[1] == "#") {
    defundef = arg[2]
    mac1 = arg[3]
  } else {
    defundef = substr(arg[1], 2)
    mac1 = arg[2]
  }
  split(mac1, mac2, "(") #)
  macro = mac2[1]
  prefix = substr(line, 1, index(line, defundef) - 1)
  if (D_is_set[macro]) {
    # Preserve the white space surrounding the "#".
    print prefix "define", macro P[macro] D[macro]
    next
  } else {
    # Replace #undef with comments.  This is necessary, for example,
    # in the case of _POSIX_SOURCE, which is predefined and required
    # on some systems where configure will not decide to define it.
    if (defundef == "undef") {
      print "/*", prefix defundef, macro, "*/"
      next
    }
  }
}
{ print }
